Feat/exceptions
viniciussaturnino/TP1-TecProg-2022-1 pull request #4
Opened 2022-07-18 18:35 UTC by matgomes21

Criação dos testes e implementação de exceções

2022-07-18 18:51 UTC, viniciussaturnino requested changes

2022-07-18 18:51 UTC, viniciussaturnino commented on app/payloads.py
> +          (type(payload.get('fraction_value')) != int or payload.get('fraction_value')<0) or
Usa o isinstance() pra verificar o tipo

2022-07-18 18:51 UTC, viniciussaturnino commented on app/payloads.py
> +          not 'license_plate' in parking_access or
`license_plate not in`

2022-07-18 23:13 UTC, thiagompc requested changes

2022-07-18 23:13 UTC, thiagompc commented on app/exceptions.py
> +        if not isinstance(daily_overnight_initial_hour, int) or daily_overnight_initial_hour<0:
daily_overnight_innitial_hour vai ser uma string no formato "HH:MM:SS"

2022-07-18 23:13 UTC, thiagompc commented on app/exceptions.py
> +        if not isinstance(daily_overnight_end_hour, int) or daily_overnight_end_hour<0:
daily_overnight_end_hour também é uma string no formato "HH:MM:SS"

2022-07-18 23:13 UTC, thiagompc commented on app/payloads.py
> +          (type(payload.get('daily_overnight_initial_hour')) != int or payload.get('daily_overnight_initial_hour')<0) or
Aqui tbm

2022-07-18 23:13 UTC, thiagompc commented on app/payloads.py
> +          (type(payload.get('daily_overnight_end_hour')) != int or payload.get('daily_overnight_end_hour')<0) or
Aqui tbm

2022-07-18 23:13 UTC, thiagompc commented on tests/test_exceptions.py
> +            daily_overnight_initial_hour=19,
Substituir para "19:00:00"

2022-07-18 23:13 UTC, thiagompc commented on tests/test_exceptions.py
> +            daily_overnight_end_hour=8,
Substituir para "08:00:00"

2022-07-18 23:16 UTC, thiagompc commented on tests/test_exceptions.py
> +            daily_overnight_end_hour=8,
Aqui tbm

2022-07-19 00:58 UTC, viniciussaturnino approved these changes

2022-07-19 01:25 UTC, viniciussaturnino approved these changes

2022-07-19 01:26 UTC, thiagompc approved these changes

2022-07-19 01:26 UTC, merged